-- MySQL Script generated by MySQL Workbench
-- Wed Jun 23 17:38:42 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipoUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipoUsuario` (
  `idTipoUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comuna` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comuna` (
  `idComuna` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idComuna`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sucursal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` INT NOT NULL AUTO_INCREMENT,
  `NombreSuc` VARCHAR(45) NOT NULL,
  `Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`idSucursal`, `Comuna_idComuna`),
  INDEX `fk_Sucursal_Comuna1_idx` (`Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Comuna1`
    FOREIGN KEY (`Comuna_idComuna`)
    REFERENCES `mydb`.`Comuna` (`idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Horario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `Disponibilidad` TINYINT NULL,
  `reserva` TINYINT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Sucursal_Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`idHorario`, `Sucursal_idSucursal`, `Sucursal_Comuna_idComuna`),
  INDEX `fk_Horario_Sucursal1_idx` (`Sucursal_idSucursal` ASC, `Sucursal_Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_Comuna_idComuna`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal` , `Comuna_idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  `Horario_Sucursal_idSucursal` INT NOT NULL,
  `Horario_Sucursal_Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `Horario_idHorario`, `Horario_Sucursal_idSucursal`, `Horario_Sucursal_Comuna_idComuna`),
  INDEX `fk_Servicio_Horario1_idx` (`Horario_idHorario` ASC, `Horario_Sucursal_idSucursal` ASC, `Horario_Sucursal_Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Horario1`
    FOREIGN KEY (`Horario_idHorario` , `Horario_Sucursal_idSucursal` , `Horario_Sucursal_Comuna_idComuna`)
    REFERENCES `mydb`.`Horario` (`idHorario` , `Sucursal_idSucursal` , `Sucursal_Comuna_idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Rut` INT(9) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `NumCelular` VARCHAR(45) NOT NULL,
  `tipoUsuario_idTipoUsuario` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Servicio_Horario_idHorario` INT NOT NULL,
  `Servicio_Horario_Sucursal_idSucursal` INT NOT NULL,
  `Servicio_Horario_Sucursal_Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Servicio_idServicio`, `Servicio_Horario_idHorario`, `Servicio_Horario_Sucursal_idSucursal`, `Servicio_Horario_Sucursal_Comuna_idComuna`),
  INDEX `fk_Usuario_tipoUsuario1_idx` (`tipoUsuario_idTipoUsuario` ASC) VISIBLE,
  INDEX `fk_Usuario_Servicio1_idx` (`Servicio_idServicio` ASC, `Servicio_Horario_idHorario` ASC, `Servicio_Horario_Sucursal_idSucursal` ASC, `Servicio_Horario_Sucursal_Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idTipoUsuario`)
    REFERENCES `mydb`.`tipoUsuario` (`idTipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Servicio1`
    FOREIGN KEY (`Servicio_idServicio` , `Servicio_Horario_idHorario` , `Servicio_Horario_Sucursal_idSucursal` , `Servicio_Horario_Sucursal_Comuna_idComuna`)
    REFERENCES `mydb`.`Servicio` (`idServicio` , `Horario_idHorario` , `Horario_Sucursal_idSucursal` , `Horario_Sucursal_Comuna_idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Hora` TIME NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva_has_Sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva_has_Sucursal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_has_Sucursal` (
  `Reserva_idReserva` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`Reserva_idReserva`, `Sucursal_idSucursal`),
  INDEX `fk_Reserva_has_Sucursal_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  INDEX `fk_Reserva_has_Sucursal_Reserva1_idx` (`Reserva_idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_has_Sucursal_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Sucursal_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva_has_Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva_has_Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva_has_Servicio` (
  `Reserva_idReserva` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`Reserva_idReserva`, `Servicio_idServicio`),
  INDEX `fk_Reserva_has_Servicio_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Reserva_has_Servicio_Reserva1_idx` (`Reserva_idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_has_Servicio_Reserva1`
    FOREIGN KEY (`Reserva_idReserva`)
    REFERENCES `mydb`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_has_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal_has_Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sucursal_has_Servicio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal_has_Servicio` (
  `Sucursal_idSucursal` INT NOT NULL,
  `Sucursal_Comuna_idComuna` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Servicio_Horario_idHorario` INT NOT NULL,
  `Servicio_Horario_Sucursal_idSucursal` INT NOT NULL,
  `Servicio_Horario_Sucursal_Comuna_idComuna` INT NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `Sucursal_Comuna_idComuna`, `Servicio_idServicio`, `Servicio_Horario_idHorario`, `Servicio_Horario_Sucursal_idSucursal`, `Servicio_Horario_Sucursal_Comuna_idComuna`),
  INDEX `fk_Sucursal_has_Servicio_Servicio1_idx` (`Servicio_idServicio` ASC, `Servicio_Horario_idHorario` ASC, `Servicio_Horario_Sucursal_idSucursal` ASC, `Servicio_Horario_Sucursal_Comuna_idComuna` ASC) VISIBLE,
  INDEX `fk_Sucursal_has_Servicio_Sucursal1_idx` (`Sucursal_idSucursal` ASC, `Sucursal_Comuna_idComuna` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_has_Servicio_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal` , `Sucursal_Comuna_idComuna`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal` , `Comuna_idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_idServicio` , `Servicio_Horario_idHorario` , `Servicio_Horario_Sucursal_idSucursal` , `Servicio_Horario_Sucursal_Comuna_idComuna`)
    REFERENCES `mydb`.`Servicio` (`idServicio` , `Horario_idHorario` , `Horario_Sucursal_idSucursal` , `Horario_Sucursal_Comuna_idComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
